FROM python:3.12

COPY --from=ghcr.io/astral-sh/uv:0.12.17 /uv /uvx /bin/

ENV PATH="/app/.venv/bin:${PATH}"

WORKDIR /app

COPY uv.lock .python-version pyproject.toml ./
RUN uv sync --locked --no-install-project

COPY src/ ./src/
COPY README.md ./
RUN uv sync --locked

COPY scripts/ingestion/ ./scripts/ingestion/

# Lascio l'entrypoint generico
#ENTRYPOINT ["uv", "run", "--module", "scripts.ingestion.ingest_player_game"]